# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mustermann-grape` gem.
# Please instead update this file by running `bin/tapioca gem mustermann-grape`.

module Mustermann
  class << self
    def [](name); end
    def extend_object(object); end
    def new(*input, type: T.unsafe(nil), operator: T.unsafe(nil), **options); end
    def normalized_type(type); end
    def register(name, type); end
    def try_require(path); end
  end
end

class Mustermann::CompileError < ::Mustermann::Error; end
Mustermann::DEFAULT_TYPE = T.let(T.unsafe(nil), Symbol)
class Mustermann::Error < ::StandardError; end
class Mustermann::ExpandError < ::Mustermann::Error; end
class Mustermann::Grape < ::Mustermann::AST::Pattern; end
class Mustermann::Grape::Parser < ::Mustermann::AST::Parser; end
class Mustermann::ParseError < ::Mustermann::Error; end
